<?xml version="1.0" encoding="UTF-8"?>
<tileset version="1.5" tiledversion="1.7.2" name="Reference Tiles" tilewidth="16" tileheight="16" tilecount="64" columns="8">
 <transformations hflip="0" vflip="0" rotate="0" preferuntransformed="1"/>
 <image source="../tileset.png" width="128" height="128"/>
 <tile id="0" type="empty"/>
 <tile id="1" type="solid_top_left"/>
 <tile id="2" type="solid_top"/>
 <tile id="3" type="solid_top_right"/>
 <tile id="4" type="solid_v_top"/>
 <tile id="5" type="slope_up"/>
 <tile id="6" type="slope_half_up_left"/>
 <tile id="7" type="slope_half_up_right"/>
 <tile id="8" type="spikes_up"/>
 <tile id="9" type="solid_left"/>
 <tile id="10" type="empty"/>
 <tile id="11" type="solid_right"/>
 <tile id="12" type="solid_v_middle"/>
 <tile id="13" type="slope_down"/>
 <tile id="14" type="slope_half_down_left"/>
 <tile id="15" type="slope_half_down_right"/>
 <tile id="16" type="spikes_right"/>
 <tile id="17" type="solid_bottom_left"/>
 <tile id="18" type="solid_bottom"/>
 <tile id="19" type="solid_bottom_right"/>
 <tile id="20" type="solid_v_bottom"/>
 <tile id="21" type="slope_double_up_top"/>
 <tile id="22" type="slope_double_down_top"/>
 <tile id="24" type="spikes_down"/>
 <tile id="25" type="solid_h_left"/>
 <tile id="26" type="solid_h_center"/>
 <tile id="27" type="solid_h_right"/>
 <tile id="28" type="solid_tile"/>
 <tile id="29" type="slope_double_up_bottom"/>
 <tile id="30" type="slope_double_down_bottom"/>
 <tile id="32" type="spikes_left"/>
 <tile id="33" type="solid_top_fade_left"/>
 <tile id="34" type="solid_top_fade_right"/>
 <tile id="35" type="solid_bottom_fade_left"/>
 <tile id="36" type="solid_bottom_fade_right"/>
 <tile id="37" type="solid_corner_bottom_right"/>
 <tile id="38" type="solid_corner_bottom_left"/>
 <tile id="41" type="solid_left_fade_top"/>
 <tile id="42" type="solid_right_fade_top"/>
 <tile id="45" type="solid_corner_top_right"/>
 <tile id="46" type="solid_corner_top_left"/>
 <tile id="49" type="solid_left_fade_bottom"/>
 <tile id="50" type="solid_right_fade_bottom"/>
 <tile id="63" type="barrier"/>
</tileset>
