<?xml version="1.0" encoding="UTF-8"?>
<tileset version="1.5" tiledversion="1.7.2" name="Reference Tiles" tilewidth="16" tileheight="16" tilecount="64" columns="8">
 <image source="../tileset.png" width="128" height="128"/>
 <tile id="0" type="solid_top_left"/>
 <tile id="1" type="solid_top"/>
 <tile id="2" type="solid_top_right"/>
 <tile id="3" type="solid_vtop"/>
 <tile id="4" type="slope_up"/>
 <tile id="5" type="slope_half_up_left"/>
 <tile id="6" type="slope_half_up_right"/>
 <tile id="8" type="solid_left"/>
 <tile id="9" type="empty"/>
 <tile id="10" type="solid_right"/>
 <tile id="11" type="solid_vmiddle"/>
 <tile id="12" type="slope_down"/>
 <tile id="13" type="slope_half_down_left"/>
 <tile id="14" type="slope_half_down_right"/>
 <tile id="16" type="solid_bottom_left"/>
 <tile id="17" type="solid_bottom"/>
 <tile id="18" type="solid_bottom_right"/>
 <tile id="19" type="solid_vbottom"/>
 <tile id="20" type="slope_double_up_top"/>
 <tile id="21" type="slope_double_down_top"/>
 <tile id="24" type="solid_hleft"/>
 <tile id="25" type="solid_hcenter"/>
 <tile id="26" type="solid_hright"/>
 <tile id="27" type="solid_tile"/>
 <tile id="28" type="slope_double_up_bottom"/>
 <tile id="29" type="slope_double_down_bottom"/>
 <tile id="32" type="spike_up"/>
 <tile id="33" type="spike_right"/>
 <tile id="34" type="spike_down"/>
 <tile id="35" type="spike_left"/>
 <tile id="40" type="solid_top"/>
 <tile id="41" type="solid_top"/>
 <tile id="42" type="solid_bottom"/>
 <tile id="43" type="solid_bottom"/>
 <tile id="48" type="solid_left"/>
 <tile id="49" type="solid_right"/>
 <tile id="56" type="solid_left"/>
 <tile id="57" type="solid_right"/>
 <tile id="63" type="barrier"/>
</tileset>
